### ISSUE TITLE
QUERY: is there any accompanying dev documents or vedios available?

### ISSUE THREAD

**Issue by chen1195585098** [gdquest-demos/godot-open-rpg#214]
Hi, thanks for you to bring such a wonderful game demo. But it is also complex for beginners, is there any accompanying dev documents or vedios for this object ?

Thanks :)

**Comment by NathanLovato** [comment]
There aren't currently, as it's in the process of being remade from scratch. Documentation would come once things get set in stone.

Please note that it's currently a project that people are working on benevolently, so there's no fixed released date for it.

I'll close this ticket as this is an inquiry. But let me know if you have more questions.
